// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAweHnhnkS4ge6plzgVOtk0O0NNYUKl4',
    appId: '1:800199246089:web:c370f87c82d751fd86d3d8',
    messagingSenderId: '800199246089',
    projectId: 'sitc-dd9a9',
    authDomain: 'sitc-dd9a9.firebaseapp.com',
    storageBucket: 'sitc-dd9a9.firebasestorage.app',
    measurementId: 'G-R6DP8F917Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxp-CLSnlHfrxlPY0djAWS4igv79TKCY',
    appId: '1:800199246089:android:741a773951f0725886d3d8',
    messagingSenderId: '800199246089',
    projectId: 'sitc-dd9a9',
    storageBucket: 'sitc-dd9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqi4ygbDMZdArG0LDz_vm5x1sTShgrMk',
    appId: '1:800199246089:ios:9b0c7ef948e2375d86d3d8',
    messagingSenderId: '800199246089',
    projectId: 'sitc-dd9a9',
    storageBucket: 'sitc-dd9a9.firebasestorage.app',
    iosBundleId: 'com.example.sairamIncubation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqi4ygbDMZdArG0LDz_vm5x1sTShgrMk',
    appId: '1:800199246089:ios:9b0c7ef948e2375d86d3d8',
    messagingSenderId: '800199246089',
    projectId: 'sitc-dd9a9',
    storageBucket: 'sitc-dd9a9.firebasestorage.app',
    iosBundleId: 'com.example.sairamIncubation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAweHnhnkS4ge6plzgVOtk0O0NNYUKl4',
    appId: '1:800199246089:web:c8e1e9e605223c0a86d3d8',
    messagingSenderId: '800199246089',
    projectId: 'sitc-dd9a9',
    authDomain: 'sitc-dd9a9.firebakseapp.com',
    storageBucket: 'sitc-dd9a9.firebasestorage.app',
    measurementId: 'G-Z6MDZ4VRSZ',
  );
}
